namespace: "sivel"
name: "jinja2"
version: "3.1.2"
readme: "README.md"
authors:
    - "sivel <matt@sivel.net>"
license_file: "LICENSE"
tags:
    - jinja
    - jinja2
repository: "https://github.com/sivel/ansible-collection-jinja2"
description: Exposes updated jinja2 filters and tests via a collection
manifest:
